### ISSUE TITLE
Is your library  support Json data output instead of JPEG ?

### ISSUE THREAD

**Issue by sonygod** [zcemycl/TF2DeepFloorplan#49]
Is your library  support Json data output instead of JPEG ?

I try to ask google bard summary your [TF2DeepFloorplan](https://github.com/zcemycl/TF2DeepFloorplan)

and got this answer

Generate a JSON file from an image:

**python dfp/deploy.py --image floorplan.jpg --weight log/store/G --postprocess --colorize --save output.json --loadmethod log**

The dfp/deploy.py script will generate a JSON file containing the floorplan for the specified image. The JSON file will be saved in the current directory with the name output.json.

Here is an example of the JSON data that will be generated:

```json
{
  "name": "My Room",
  "dimensions": {
    "width": 10,
    "height": 10
  },
  "walls": [
    {
      "start": {
        "x": 0,
        "y": 0
      },
      "end": {
        "x": 10,
        "y": 0
      }
    },
    {
      "start": {
        "x": 10,
        "y": 0
      },
      "end": {
        "x": 10,
        "y": 10
      }
    },
    {
      "start": {
        "x": 10,
        "y": 10
      },
      "end": {
        "x": 0,
        "y": 10
      }
    },
    {
      "start": {
        "x": 0,
        "y": 10
      },
      "end": {
        "x": 0,
        "y": 0
      }
    }
  ],
  "doors": [
    {
      "position": {
        "x": 5,
        "y": 5
      }
    }
  ],
  "windows": [
    {
      "position": {
        "x": 2,
        "y": 2
      },
      "size": {
        "width": 1,
        "height": 1
      }
    },
    {
      "position": {
        "x": 8,
        "y": 8
      },
      "size": {
        "width": 1,
        "height": 1
      }
    }
  ]
}
```

<img width="1029" alt="image" src="https://github.com/zcemycl/TF2DeepFloorplan/assets/748320/70561ca2-244b-406e-952b-7594199c75b2">

**Comment by zcemycl** [comment]
No, dfp.deploy does not generate json. Bard has no idea about most of the open source code, please don't trust it.

It only generates png or jpg.

**Comment by massimilianoperelli** [comment]
I've two questions, maybe silly questions since I'm new to this topic:

This is one of my results training the model on my own

/home/fscloud-dev/dev-hacka-23/TF2DeepFloorplan/src/1.jpg

/home/fscloud-dev/dev-hacka-23/TF2DeepFloorplan/src/output.jpg

1) There is a way to use a pre trained model instead of running the training? Maybe one that uses also the mentioned dataset r2v to obtain better results?

2) The output now is a jpg, as @sonygod mentions, it would be nice to have a json output.
What I'm looking for at the moment is a list of rooms, maybe with X,Y of coordinates which compose rooms boundaries. Which would be the fastest way to obtain this? should have a look in some specific part of the code and modifying it? Or it is a too big goal to be reached in terms of effort?

Now I saw this brand new pygame feature which makes me think this is possible.

**Comment by zcemycl** [comment]
@massimilianoperelli 

1. I have my pretrained model for this (not training on r2v, but only on r3d), you can download it from google drive in readme. 
2. Eh... If you run my notebook, you can see you are deploying the pretrained model with `main` function. If you set the `argparse.Namespace` with settings `colorize = False`, it will return you an image with 0-10 classes, each pixel is a class. If you use `np.where(result==class_id)`, you will get all xy coordinates for specific class.
