### ISSUE TITLE
postprocessing function

### ISSUE THREAD

**Issue by Sina-Tavasoli** [zcemycl/TF2DeepFloorplan#9]
Hello and thank you for the code.
I have followed the colab page.
Firstly, the Log file cannot be downloaded because I guess it needs your authorization. But, that is not the main issue. 
In the postprocessing function (cell number 10), I keep receiving an error indicating that "cannot reshape array of size 262144 into shape (600,419, newaxis)"
I what is the problem with that.

Appreciate it if you could help me with that.
Regards.

**Comment by zcemycl** [comment]
@Sina-Tavasoli 
1. I will check my google drive later. 

2. Whats your image dimension? Whats your input dimension before postprocessing?

**Comment by Sina-Tavasoli** [comment]
Thanks for the response,
Actually, I did not change the image and I am using the same image as it is in your colab notebook. It was 600*419 I guess.

![image](https://user-images.githubusercontent.com/90361685/154822463-7bd51d93-6dfd-47fc-b394-7c8a85b3f66e.png)

**Comment by zcemycl** [comment]
@Sina-Tavasoli 
1. I checked my google drive, it is still public. This is caused by gdown failure. I added extra line to fix it already. Now you can download log zip.
2. This is my mistake, the main function works well. But when breaking down the steps, I forget to include the tf resize. 

Please check the colab notebook again. Please star or fork my repo if it is useful for your work.

**Comment by Sina-Tavasoli** [comment]
Sure. Thanks for your help.
